### ISSUE TITLE
Modifier.applyQuackSize 에서 width 가 적용되지 않음

### ISSUE THREAD

**Issue by EvergreenTree97** [sungbinland/duckie-quack-quack#56]
~~1. `QuackSurface` 에서 `animateContentSize` 가 적용되고 있는데, Size 가 고정돼야 하는 컴포넌트들도 적용되고 있음~~ **[[INVALID]](https://github.com/sungbinland/duckie-quack-quack/issues/56#issuecomment-1224475044)**
2. `Modifier.applyQuackSize` 에서 인자로 받는 `width` 와 `height` 중에서  `height` 만 적용됨

**Comment by jisungbin** [comment]
@EvergreenTree97 제보 감사합니다. 혹시 1번 현상 더 자세한 설명 가능할까요?

**Comment by EvergreenTree97** [comment]
> @EvergreenTree97 제보 감사합니다. 혹시 1번 현상 더 자세한 설명 가능할까요? Size 가 고정돼야 하는 컴포넌트들에는 Size 변동을 주지 않으면 애니메이션이 적용되지 않습니다. 애니메이션이 없어야 하는 컴포넌트까지 애니메니션이 적용되고 있다는 말씀이실까요?

네 TextField같은 경우 Size 변동 애니메이션을 적용해야 하는 경우도 있지만, 아래와 같은 경우 Text가 Width를 넘어갔을 때 사이즈가 조정되지 않아야 하는 경우도 존재합니다
![image](https://user-images.githubusercontent.com/70064912/186229019-f016045f-96f6-4f13-abad-4a50c5eea5e1.png)

**Comment by jisungbin** [comment]
> > @EvergreenTree97 제보 감사합니다. 혹시 1번 현상 더 자세한 설명 가능할까요? Size 가 고정돼야 하는 컴포넌트들에는 Size 변동을 주지 않으면 애니메이션이 적용되지 않습니다. 애니메이션이 없어야 하는 컴포넌트까지 애니메니션이 적용되고 있다는 말씀이실까요?
> 
> 네 TextField같은 경우 Size 변동 애니메이션을 적용해야 하는 경우도 있지만, 아래와 같은 경우 Text가 Width를 넘어갔을 때 사이즈가 조정되지 않아야 하는 경우도 존재합니다 ![image](https://user-images.githubusercontent.com/70064912/186229019-f016045f-96f6-4f13-abad-4a50c5eea5e1.png)

그럼 이게 고쳐지기 위해선 특정 Size 로 고정하는 기능이 필요하다는 말씀이신거죠?

**Comment by EvergreenTree97** [comment]
> > > @EvergreenTree97 제보 감사합니다. 혹시 1번 현상 더 자세한 설명 가능할까요? Size 가 고정돼야 하는 컴포넌트들에는 Size 변동을 주지 않으면 애니메이션이 적용되지 않습니다. 애니메이션이 없어야 하는 컴포넌트까지 애니메니션이 적용되고 있다는 말씀이실까요?
> > 
> > 
> > 네 TextField같은 경우 Size 변동 애니메이션을 적용해야 하는 경우도 있지만, 아래와 같은 경우 Text가 Width를 넘어갔을 때 사이즈가 조정되지 않아야 하는 경우도 존재합니다
> > ![image](https://user-images.githubusercontent.com/70064912/186229019-f016045f-96f6-4f13-abad-4a50c5eea5e1.png)
> 
> 그럼 이게 고쳐지기 위해선 특정 Size 로 고정하는 기능이 필요하다는 말씀이신거죠?

넵!

**Comment by jisungbin** [comment]
> 네 그렇습니다

해당 기능이라면 이미 있습니다. [Quack[Height/width].custom](https://quack-docs.duckie.team/ui-components/team.duckie.quackquack.ui.constant/-quack-width/index.html#-1627709782%2FClasslikes%2F-2017335210).

**Comment by jisungbin** [comment]
> 2. `Modifier.applyQuackSize` 에서 인자로 받는 `width` 와 `height` 중에서  `height` 만 적용됨

1번 항목은 invalid 하고, 2번 항목은 제가 다시 확인 해보겠습니다. 감사합니다.

**Comment by EvergreenTree97** [comment]
> > 네 그렇습니다
> 
> 해당 기능이라면 이미 있습니다. [QuackHeight.Custom(height: Dp)](https://quack-docs.duckie.team/ui-components/team.duckie.quackquack.ui.constant/-quack-height/-custom/index.html), [QuackWidth.Custom(width:Dp)](https://quack-docs.duckie.team/ui-components/team.duckie.quackquack.ui.constant/-quack-width/-custom/index.html)를 참고해 주세요.
> 
> 아직 문서화가 덜 된점 양해 부탁드립니다. 제가 디자인 시스템 작업 시작하는대로 다 문서화가 진행될 예정입니다.

위 내용에 대해서는 인지하고 있습니다. 따로 트래킹 했던 결과 default로 animateContentSize를 적용하고 있는 것이 QuackSurface를 부모로 두는 컴포넌트들에게 가변 크기가 적용되는 이유임을 확인했습니다. 제가 잘못 알고 있는걸까요?
```
@Composable
internal fun QuackSurface(
    modifier: Modifier = Modifier,
    ...
) {
    Box(
        modifier = modifier
           ...
            .animateContentSize(
                animationSpec = quackTween(),
            ),
        ...
    )
}
```

**Comment by jisungbin** [comment]
`[Modifier.animateContentSize](https://developer.android.com/jetpack/compose/animation#animateContentSize)` 는 컴포저블 사이즈가 변경되면 사이즈 변경 애니메이션을 적용하는 [Modifier](https://developer.android.com/reference/kotlin/androidx/compose/ui/Modifier) 로, 컴포저블의 사이즈를 직접적으로 조정하진 않습니다.

**Comment by EvergreenTree97** [comment]
GOTCHA,, 해당 답변으로 이슈 생성 필요가 없을 것 같습니다 감사합니다

> [`Modifier.animateContentSize`](https://developer.android.com/jetpack/compose/animation#animateContentSize) 는 컴포저블 사이즈가 변경되면 사이즈 변경 애니메이션을 적용하는 [Modifier](https://developer.android.com/reference/kotlin/androidx/compose/ui/Modifier) 로, **컴포저블의 사이즈를 직접적으로 조정하진 않습니다**.

**Comment by jisungbin** [comment]
## 해결

https://github.com/sungbinland/duckie-quack-quack/pull/75
